name: Create S3 Static Site

on: 
  issues:
    type:
      -opened

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Debug - Verify Secrets are Loaded
        run: |
          if [ -z "${{ secrets.AWS_ACCESS_KEY_ID }}" ]; then
            echo "❌ ERRO: O secret AWS_ACCESS_KEY_ID não foi encontrado ou está vazio."
            exit 1
          else
            echo "✅ SUCESSO: O secret AWS_ACCESS_KEY_ID foi carregado."
          fi

          if [ -z "${{ secrets.AWS_SECRET_ACCESS_KEY }}" ]; then
            echo "❌ ERRO: O secret AWS_SECRET_ACCESS_KEY não foi encontrado ou está vazio."
            exit 1
          else
            echo "✅ SUCESSO: O secret AWS_SECRET_ACCESS_KEY foi carregado."
          fi

          if [ -z "${{ secrets.GITHUB_TOKEN }}" ]; then
            echo "⚠️ AVISO: O secret GITHUB_TOKEN não está disponível. O passo de comentar na issue pode falhar."
          else
            echo "✅ SUCESSO: O secret GITHUB_TOKEN foi carregado."
          fi

      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v4

      - name: Extract Bucket Name from Issue 
        run: |
          export BUCKET_NAME=$(echo "${{ github.event.issue.title }}")
          echo "Bucket Name: $BUCKET_NAME"
          echo "BUCKET_NAME=$BUCKET_NAME" >> $GITHUB_ENV

      - name: Run Terraform
        run: |
          cd terraform
          cd s3-bucket-static
          terraform init
          terraform apply -auto-approve -var="bucket_name=${{ env.BUCKET_NAME }}"
      
      - name: Add comment
        run: gh issue comment "$NUMBER" --repo "$REPO" --body "$BODY"
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          NUMBER: ${{ github.event.issue.number }}
          REPO: ${{ github.repository }}
          BODY: >
            0 bucket s3 foi criado com sucesso! 